import { Button } from "@/components/ui/button";
import { ArrowRight, CheckCircle2, Download, ShieldCheck, Smartphone } from "lucide-react";

const apkUrl = "/download/Lahza-v1.8.0-release-signed.apk";

export default function DownloadApp() {
  return <main dir="rtl" className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-100 bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-4"><a href="/" className="text-2xl font-black text-blue-900">لحظة<span className="text-red-600">•</span></a><a href="/" className="inline-flex items-center gap-2 text-sm font-bold text-blue-900"><ArrowRight className="h-4 w-4" />العودة للموقع</a></div></header><section className="mx-auto max-w-4xl px-5 py-12 sm:py-20"><div className="overflow-hidden rounded-[2rem] bg-blue-900 p-7 text-white shadow-2xl sm:p-12"><div className="max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-bold text-blue-100"><Smartphone className="h-4 w-4" />تطبيق Android الرسمي</span><h1 className="mt-5 text-3xl font-black leading-tight sm:text-5xl">حمّل تطبيق لحظة<br /><span className="text-red-300">بخطوة واحدة.</span></h1><p className="mt-5 max-w-xl text-sm leading-7 text-blue-100 sm:text-base">اطلب احتياجاتك، استعلم عن الفاتورة، وشارك موقعك من هاتفك بسهولة. هذه النسخة مخصصة لأجهزة Android.</p><a href={apkUrl} download="Lahza-v1.8.0-release.apk" className="mt-8 inline-block"><Button size="lg" className="h-14 rounded-2xl bg-red-600 px-6 text-base font-black hover:bg-red-700"><Download className="h-5 w-5" />تحميل تطبيق لحظة — APK</Button></a><p className="mt-3 text-xs text-blue-200">الإصدار 1.8.0 · حزمة موقعة رسمياً</p></div></div><div className="mt-8 grid gap-4 md:grid-cols-3"><Step number="١" title="نزّل الملف" text="اضغط زر التحميل وانتظر حتى يكتمل تنزيل ملف APK." /><Step number="٢" title="اسمح بالتثبيت" text="إذا طلب هاتفك ذلك، اسمح للمتصفح بتثبيت التطبيقات من هذا المصدر." /><Step number="٣" title="افتح لحظة" text="اضغط تثبيت ثم افتح التطبيق، واسمح بالموقع عند طلبه لإتمام الفاتورة." /></div><section className="mt-8 rounded-3xl border border-emerald-100 bg-emerald-50 p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-700" /><div><h2 className="font-black text-emerald-950">نصائح للتحديث</h2><p className="mt-1 text-sm leading-6 text-emerald-900">احفظ هذا الرابط. عند توفر إصدار أحدث، حمّل النسخة الجديدة من الصفحة نفسها وثبّتها فوق التطبيق الحالي للاحتفاظ ببياناته.</p></div></div></section></section><footer className="pb-8 text-center text-xs font-medium tracking-wide text-slate-400" dir="ltr">Designed by Ahmad barho</footer></main>;
}

function Step({ number, title, text }: { number: string; title: string; text: string }) {
  return <article className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-red-50 text-sm font-black text-red-600">{number}</span><h2 className="mt-4 font-black text-blue-900">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p><CheckCircle2 className="mt-4 h-5 w-5 text-emerald-500" /></article>;
}
